<?php
/*
 * This file was generated by modelGen
 * VERSION: c58b306895e4c9c3d8ced1b38b3d780b
 * https://github.com/alexshadie/modelGen
 */

namespace alexshadie\currency;

class FiatCurrency 
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $code;

    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $unit;

    /**
     * @var int|null
     */
    private $countryId;

    /**
     * @var string
     */
    private $countryName;

    public function __construct(int $id, string $code, string $name, int $unit, ?int $countryId, string $countryName)
    {
        $this->id = $id;
        $this->code = $code;
        $this->name = $name;
        $this->unit = $unit;
        $this->countryId = $countryId;
        $this->countryName = $countryName;
    }

    public static function build(): FiatCurrencyBuilder
    {
        return new FiatCurrencyBuilder();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function getUnit(): int
    {
        return $this->unit;
    }

    public function getCountryId(): ?int
    {
        return $this->countryId;
    }

    public function getCountryName(): string
    {
        return $this->countryName;
    }

    public function equals(?FiatCurrency $src): bool
    {
        if (is_null($src)) {
            return false;
        }
        return
            $this->getId() === $src->getId() &&
            $this->getCode() === $src->getCode() &&
            $this->getName() === $src->getName() &&
            $this->getUnit() === $src->getUnit() &&
            $this->getCountryId() === $src->getCountryId() &&
            $this->getCountryName() === $src->getCountryName() 
        ;
    }
}
