<?php
/*
 * This file was generated by modelGen
 * VERSION: 8fcd516e165de2905616708ad5fccec8
 * https://github.com/alexshadie/modelGen
 */

namespace alexshadie\currency;

use PHPUnit\Framework\TestCase;

class CryptoCurrencyTest extends TestCase
{

    public function testCreate()
    {
        $m = new CryptoCurrency(
            28,
            "z2mjjd5krghpa8pr",
            "nx1hgo3k4m6v7z9m",
            "rsiaq7dj14fjf2po",
            ["vigzwm4p9lq057jl"],
            ["sx4axn0bhcvfvtt2"],
            ["63j1kcjwbpzhife5"],
            "nah4r0n31vccpaqb",
            62,
            30.5,
            "4wiw0g4852ndgk6p",
            "pm18fztbhyjmwu6a",
            "v3m2j6qk8066ygoh",
            true
        );

        $this->assertEquals(28, $m->getId());
        $this->assertEquals("z2mjjd5krghpa8pr", $m->getCode());
        $this->assertEquals("nx1hgo3k4m6v7z9m", $m->getName());
        $this->assertEquals("rsiaq7dj14fjf2po", $m->getLogo());
        $this->assertEquals(["vigzwm4p9lq057jl"], $m->getExplorer());
        $this->assertEquals(["sx4axn0bhcvfvtt2"], $m->getSite());
        $this->assertEquals(["63j1kcjwbpzhife5"], $m->getChat());
        $this->assertEquals("nah4r0n31vccpaqb", $m->getAnnouncement());
        $this->assertEquals(62, $m->getConfirmations());
        $this->assertEquals(30.5, $m->getSupply());
        $this->assertEquals("4wiw0g4852ndgk6p", $m->getSourceCode());
        $this->assertEquals("pm18fztbhyjmwu6a", $m->getDocumentation());
        $this->assertEquals("v3m2j6qk8066ygoh", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $m = (new CryptoCurrencyBuilder())
            ->setId(9)
            ->setCode("tfd2wddrxmisbapx")
            ->setName("pdo6mth44wzvqgsd")
            ->setLogo("cediqxmjxxiietjl")
            ->setExplorer(["jvzb7nf325ll04fh"])
            ->setSite(["m778rqcvc4ows9tb"])
            ->setChat(["bg30vhauxkgd93ww"])
            ->setAnnouncement("qlbec68z5u7yw1pv")
            ->setConfirmations(93)
            ->setSupply(71.5)
            ->setSourceCode("69qyg6lsghekgo7e")
            ->setDocumentation("4ikp8j8jnpoypyc4")
            ->setType("txz2rkkbzqfbm3ao")
            ->setIsMineable(false)
            ->create();

        $this->assertEquals(9, $m->getId());
        $this->assertEquals("tfd2wddrxmisbapx", $m->getCode());
        $this->assertEquals("pdo6mth44wzvqgsd", $m->getName());
        $this->assertEquals("cediqxmjxxiietjl", $m->getLogo());
        $this->assertEquals(["jvzb7nf325ll04fh"], $m->getExplorer());
        $this->assertEquals(["m778rqcvc4ows9tb"], $m->getSite());
        $this->assertEquals(["bg30vhauxkgd93ww"], $m->getChat());
        $this->assertEquals("qlbec68z5u7yw1pv", $m->getAnnouncement());
        $this->assertEquals(93, $m->getConfirmations());
        $this->assertEquals(71.5, $m->getSupply());
        $this->assertEquals("69qyg6lsghekgo7e", $m->getSourceCode());
        $this->assertEquals("4ikp8j8jnpoypyc4", $m->getDocumentation());
        $this->assertEquals("txz2rkkbzqfbm3ao", $m->getType());
        $this->assertEquals(false, $m->getIsMineable());

        $src = [];
        $src['id'] = 2;
        $src['code'] = "ckpm1e7u4nd8ipnu";
        $src['name'] = "rxij5ugnpswlust7";
        $src['logo'] = "alevgflausuy04bi";
        $src['explorer'] = ["vahj216397hzhalo"];
        $src['site'] = ["upxtnrgn1xbu0jtc"];
        $src['chat'] = ["5f0hi9rv9348n4fi"];
        $src['announcement'] = "mmmjj4bb3qowzuid";
        $src['confirmations'] = 12;
        $src['supply'] = 55.5;
        $src['sourceCode'] = "twqoumy143vn41pt";
        $src['documentation'] = "2nz7ham9a1w1kk3g";
        $src['type'] = "jmw06aep6wgkfff7";
        $src['isMineable'] = true;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(2, $m->getId());
        $this->assertEquals("ckpm1e7u4nd8ipnu", $m->getCode());
        $this->assertEquals("rxij5ugnpswlust7", $m->getName());
        $this->assertEquals("alevgflausuy04bi", $m->getLogo());
        $this->assertEquals(["vahj216397hzhalo"], $m->getExplorer());
        $this->assertEquals(["upxtnrgn1xbu0jtc"], $m->getSite());
        $this->assertEquals(["5f0hi9rv9348n4fi"], $m->getChat());
        $this->assertEquals("mmmjj4bb3qowzuid", $m->getAnnouncement());
        $this->assertEquals(12, $m->getConfirmations());
        $this->assertEquals(55.5, $m->getSupply());
        $this->assertEquals("twqoumy143vn41pt", $m->getSourceCode());
        $this->assertEquals("2nz7ham9a1w1kk3g", $m->getDocumentation());
        $this->assertEquals("jmw06aep6wgkfff7", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $src = [];
        $src[0] = 91;
        $src[1] = "5oq45ierq0h0d35q";
        $src[2] = "xgbjmcu66nnhqrrx";
        $src[3] = "iejbmlvies5s301n";
        $src[4] = ["ru57n1yj8mxu9rli"];
        $src[5] = ["3jncku1wqeew4nx3"];
        $src[6] = ["ys3ao9lqr4sxiw2y"];
        $src[7] = "2mjm47vdqs71y57x";
        $src[8] = 95;
        $src[9] = 78.5;
        $src[10] = "ksigfhnr5or6lurr";
        $src[11] = "cnj99mripra0o5xn";
        $src[12] = "zdi6kryd54k8e04d";
        $src[13] = true;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(91, $m->getId());
        $this->assertEquals("5oq45ierq0h0d35q", $m->getCode());
        $this->assertEquals("xgbjmcu66nnhqrrx", $m->getName());
        $this->assertEquals("iejbmlvies5s301n", $m->getLogo());
        $this->assertEquals(["ru57n1yj8mxu9rli"], $m->getExplorer());
        $this->assertEquals(["3jncku1wqeew4nx3"], $m->getSite());
        $this->assertEquals(["ys3ao9lqr4sxiw2y"], $m->getChat());
        $this->assertEquals("2mjm47vdqs71y57x", $m->getAnnouncement());
        $this->assertEquals(95, $m->getConfirmations());
        $this->assertEquals(78.5, $m->getSupply());
        $this->assertEquals("ksigfhnr5or6lurr", $m->getSourceCode());
        $this->assertEquals("cnj99mripra0o5xn", $m->getDocumentation());
        $this->assertEquals("zdi6kryd54k8e04d", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $src = [];
        $src['id'] = 88;
        $src['code'] = "3wmo401kl1xj5y7m";
        $src['name'] = "ii2i6d32y1nrqn3w";
        $src['logo'] = "qlfmp4mhkm39xmoa";
        $src['explorer'] = ["lq5wxa1qzcxnyceh"];
        $src['site'] = ["ew5qes89x2812pjq"];
        $src['chat'] = ["7mklqz0iibzy1gxh"];
        $src['announcement'] = "effns0pu5w7p8k38";
        $src['confirmations'] = 15;
        $src['supply'] = 71.5;
        $src['source_code'] = "7rzhb2cquglnnfjh";
        $src['documentation'] = "knsuhbobpojotavv";
        $src['type'] = "j7r8dytjyo8zafqo";
        $src['is_mineable'] = true;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(88, $m->getId());
        $this->assertEquals("3wmo401kl1xj5y7m", $m->getCode());
        $this->assertEquals("ii2i6d32y1nrqn3w", $m->getName());
        $this->assertEquals("qlfmp4mhkm39xmoa", $m->getLogo());
        $this->assertEquals(["lq5wxa1qzcxnyceh"], $m->getExplorer());
        $this->assertEquals(["ew5qes89x2812pjq"], $m->getSite());
        $this->assertEquals(["7mklqz0iibzy1gxh"], $m->getChat());
        $this->assertEquals("effns0pu5w7p8k38", $m->getAnnouncement());
        $this->assertEquals(15, $m->getConfirmations());
        $this->assertEquals(71.5, $m->getSupply());
        $this->assertEquals("7rzhb2cquglnnfjh", $m->getSourceCode());
        $this->assertEquals("knsuhbobpojotavv", $m->getDocumentation());
        $this->assertEquals("j7r8dytjyo8zafqo", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $m = CryptoCurrency::build()
            ->setId(9)
            ->setCode("tfd2wddrxmisbapx")
            ->setName("pdo6mth44wzvqgsd")
            ->setLogo("cediqxmjxxiietjl")
            ->setExplorer(["jvzb7nf325ll04fh"])
            ->setSite(["m778rqcvc4ows9tb"])
            ->setChat(["bg30vhauxkgd93ww"])
            ->setAnnouncement("qlbec68z5u7yw1pv")
            ->setConfirmations(93)
            ->setSupply(71.5)
            ->setSourceCode("69qyg6lsghekgo7e")
            ->setDocumentation("4ikp8j8jnpoypyc4")
            ->setType("txz2rkkbzqfbm3ao")
            ->setIsMineable(false)
            ->create();
        $this->assertEquals(9, $m->getId());
        $this->assertEquals("tfd2wddrxmisbapx", $m->getCode());
        $this->assertEquals("pdo6mth44wzvqgsd", $m->getName());
        $this->assertEquals("cediqxmjxxiietjl", $m->getLogo());
        $this->assertEquals(["jvzb7nf325ll04fh"], $m->getExplorer());
        $this->assertEquals(["m778rqcvc4ows9tb"], $m->getSite());
        $this->assertEquals(["bg30vhauxkgd93ww"], $m->getChat());
        $this->assertEquals("qlbec68z5u7yw1pv", $m->getAnnouncement());
        $this->assertEquals(93, $m->getConfirmations());
        $this->assertEquals(71.5, $m->getSupply());
        $this->assertEquals("69qyg6lsghekgo7e", $m->getSourceCode());
        $this->assertEquals("4ikp8j8jnpoypyc4", $m->getDocumentation());
        $this->assertEquals("txz2rkkbzqfbm3ao", $m->getType());
        $this->assertEquals(false, $m->getIsMineable());

    }

    public function testCreateNulls()
    {
        $m = new CryptoCurrency(
            88,
            "duzbrx0779ccc5fo",
            "rjb6926rvyxl3jna",
            null,
            ["adlwvi429q7b83fs"],
            ["2fbxd7z9mt2czprt"],
            ["fcfqf7odg0tsn7me"],
            null,
            null,
            null,
            null,
            null,
            "javwfn57hilkks4d",
            true
        );

        $this->assertEquals(88, $m->getId());
        $this->assertEquals("duzbrx0779ccc5fo", $m->getCode());
        $this->assertEquals("rjb6926rvyxl3jna", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["adlwvi429q7b83fs"], $m->getExplorer());
        $this->assertEquals(["2fbxd7z9mt2czprt"], $m->getSite());
        $this->assertEquals(["fcfqf7odg0tsn7me"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("javwfn57hilkks4d", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $m = (new CryptoCurrencyBuilder())
            ->setId(13)
            ->setCode("w4fbkldatwo7z0y9")
            ->setName("pzgcy07q8n5cs2a1")
            ->setLogo(null)
            ->setExplorer(["zvo36x5jd3ucnggb"])
            ->setSite(["5euc6drq1mo5dy58"])
            ->setChat(["k06ou1exh62ri910"])
            ->setAnnouncement(null)
            ->setConfirmations(null)
            ->setSupply(null)
            ->setSourceCode(null)
            ->setDocumentation(null)
            ->setType("eavjhunxbe9rdww2")
            ->setIsMineable(true)
            ->create();

        $this->assertEquals(13, $m->getId());
        $this->assertEquals("w4fbkldatwo7z0y9", $m->getCode());
        $this->assertEquals("pzgcy07q8n5cs2a1", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["zvo36x5jd3ucnggb"], $m->getExplorer());
        $this->assertEquals(["5euc6drq1mo5dy58"], $m->getSite());
        $this->assertEquals(["k06ou1exh62ri910"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("eavjhunxbe9rdww2", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $src = [];
        $src['id'] = 53;
        $src['code'] = "xjavp8938xumo4tz";
        $src['name'] = "6o4hkqxubjxg0v87";
        $src['logo'] = null;
        $src['explorer'] = ["ro67pypeannk4k8h"];
        $src['site'] = ["6alyybwszo1qx57c"];
        $src['chat'] = ["odzgdvu3qoe58g4n"];
        $src['announcement'] = null;
        $src['confirmations'] = null;
        $src['supply'] = null;
        $src['sourceCode'] = null;
        $src['documentation'] = null;
        $src['type'] = "7apo8fzc6fb5711d";
        $src['isMineable'] = true;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(53, $m->getId());
        $this->assertEquals("xjavp8938xumo4tz", $m->getCode());
        $this->assertEquals("6o4hkqxubjxg0v87", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["ro67pypeannk4k8h"], $m->getExplorer());
        $this->assertEquals(["6alyybwszo1qx57c"], $m->getSite());
        $this->assertEquals(["odzgdvu3qoe58g4n"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("7apo8fzc6fb5711d", $m->getType());
        $this->assertEquals(true, $m->getIsMineable());

        $src = [];
        $src[0] = 6;
        $src[1] = "kifbtuwh9f31jt1o";
        $src[2] = "vz5hrieva94t0w87";
        $src[3] = null;
        $src[4] = ["9oto0sn04k3enmsh"];
        $src[5] = ["ag7lejy1ixkqmz6z"];
        $src[6] = ["et6lcf48jmx2h2gg"];
        $src[7] = null;
        $src[8] = null;
        $src[9] = null;
        $src[10] = null;
        $src[11] = null;
        $src[12] = "gzif5m21d554rjdn";
        $src[13] = false;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(6, $m->getId());
        $this->assertEquals("kifbtuwh9f31jt1o", $m->getCode());
        $this->assertEquals("vz5hrieva94t0w87", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["9oto0sn04k3enmsh"], $m->getExplorer());
        $this->assertEquals(["ag7lejy1ixkqmz6z"], $m->getSite());
        $this->assertEquals(["et6lcf48jmx2h2gg"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("gzif5m21d554rjdn", $m->getType());
        $this->assertEquals(false, $m->getIsMineable());

        $src = [];
        $src['id'] = 57;
        $src['code'] = "v2tust1e9a38pcge";
        $src['name'] = "8s95w6jl1crd9u21";
        $src['logo'] = null;
        $src['explorer'] = ["vthm8d1y7iyub8jj"];
        $src['site'] = ["3y7skooeqali2w41"];
        $src['chat'] = ["3y4il3nl6sqxzd3p"];
        $src['announcement'] = null;
        $src['confirmations'] = null;
        $src['supply'] = null;
        $src['source_code'] = null;
        $src['documentation'] = null;
        $src['type'] = "gzfoa3t0xfius1s2";
        $src['is_mineable'] = false;
        $m = CryptoCurrencyBuilder::fromArray($src)
            ->create();
        $this->assertEquals(57, $m->getId());
        $this->assertEquals("v2tust1e9a38pcge", $m->getCode());
        $this->assertEquals("8s95w6jl1crd9u21", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["vthm8d1y7iyub8jj"], $m->getExplorer());
        $this->assertEquals(["3y7skooeqali2w41"], $m->getSite());
        $this->assertEquals(["3y4il3nl6sqxzd3p"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("gzfoa3t0xfius1s2", $m->getType());
        $this->assertEquals(false, $m->getIsMineable());

        $m = CryptoCurrency::build()
            ->setId(79)
            ->setCode("o16bcumrbdgpv8hi")
            ->setName("ivbh09byso78aif8")
            ->setLogo(null)
            ->setExplorer(["jefofy3nkm5iz7ik"])
            ->setSite(["hisixz3vwijhu7yo"])
            ->setChat(["6d0y3cy6zlyw1y6q"])
            ->setAnnouncement(null)
            ->setConfirmations(null)
            ->setSupply(null)
            ->setSourceCode(null)
            ->setDocumentation(null)
            ->setType("ztldj1z5wltq37xz")
            ->setIsMineable(false)
            ->create();
        $this->assertEquals(79, $m->getId());
        $this->assertEquals("o16bcumrbdgpv8hi", $m->getCode());
        $this->assertEquals("ivbh09byso78aif8", $m->getName());
        $this->assertEquals(null, $m->getLogo());
        $this->assertEquals(["jefofy3nkm5iz7ik"], $m->getExplorer());
        $this->assertEquals(["hisixz3vwijhu7yo"], $m->getSite());
        $this->assertEquals(["6d0y3cy6zlyw1y6q"], $m->getChat());
        $this->assertEquals(null, $m->getAnnouncement());
        $this->assertEquals(null, $m->getConfirmations());
        $this->assertEquals(null, $m->getSupply());
        $this->assertEquals(null, $m->getSourceCode());
        $this->assertEquals(null, $m->getDocumentation());
        $this->assertEquals("ztldj1z5wltq37xz", $m->getType());
        $this->assertEquals(false, $m->getIsMineable());

    }

    public function testEquals()
    {
        $m = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $me = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneId = new CryptoCurrency(
            5,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneCode = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf" . "123",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneName = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz" . "123",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneLogo = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht" . "123",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneExplorer = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0abc"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneSite = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1afabc"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneChat = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4clabc"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneAnnouncement = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu" . "123",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneConfirmations = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            41,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneSupply = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            19.8,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneSourceCode = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l" . "123",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneDocumentation = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz" . "123",
            "2jpaoxwej5hhieg4",
            true
        );

        $mneType = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4" . "123",
            true
        );

        $mneIsMineable = new CryptoCurrency(
            4,
            "2yira1m4hrqnybvf",
            "o7raakps95hvhayz",
            "wabs8a1m22pjz0ht",
            ["49eswvgkxgpxmuw0"],
            ["kodlwfs9zaloc1af"],
            ["r2rshjvu7n29d4cl"],
            "o1wqqkyl38wq7bmu",
            40,
            18.5,
            "wtogltp98nywfv9l",
            "fvncami074kl3vaz",
            "2jpaoxwej5hhieg4",
            false
        );

        $this->assertTrue($m->equals($me));
        $this->assertTrue($me->equals($m));
        $this->assertFalse($m->equals(null));
        $this->assertFalse($m->equals($mneId));
        $this->assertFalse($mneId->equals($m));
        $this->assertFalse($m->equals($mneCode));
        $this->assertFalse($mneCode->equals($m));
        $this->assertFalse($m->equals($mneName));
        $this->assertFalse($mneName->equals($m));
        $this->assertFalse($m->equals($mneLogo));
        $this->assertFalse($mneLogo->equals($m));
        $this->assertFalse($m->equals($mneExplorer));
        $this->assertFalse($mneExplorer->equals($m));
        $this->assertFalse($m->equals($mneSite));
        $this->assertFalse($mneSite->equals($m));
        $this->assertFalse($m->equals($mneChat));
        $this->assertFalse($mneChat->equals($m));
        $this->assertFalse($m->equals($mneAnnouncement));
        $this->assertFalse($mneAnnouncement->equals($m));
        $this->assertFalse($m->equals($mneConfirmations));
        $this->assertFalse($mneConfirmations->equals($m));
        $this->assertFalse($m->equals($mneSupply));
        $this->assertFalse($mneSupply->equals($m));
        $this->assertFalse($m->equals($mneSourceCode));
        $this->assertFalse($mneSourceCode->equals($m));
        $this->assertFalse($m->equals($mneDocumentation));
        $this->assertFalse($mneDocumentation->equals($m));
        $this->assertFalse($m->equals($mneType));
        $this->assertFalse($mneType->equals($m));
        $this->assertFalse($m->equals($mneIsMineable));
        $this->assertFalse($mneIsMineable->equals($m));
    }
}
